<BoundingBox>:
  canvas.after:
    Color:
      rgba: (1, 0, 0, 1)
    Line:
      points: [self.x, self.y, self.x + self.width, self.y, self.x + self.width, self.y + self.height, self.x, self.y + self.height, self.x, self.y]
      width: 2

  size_hint: (None, None)
  width: self.scaler.value*self.max_width
  height: self.scaler.value*self.max_height

  drag_rectangle: self.x, self.y, self.width, self.height
  drag_timeout: 10000000
  drag_distance: 0
